name: liquid
description: Liquid application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cached_network_image: ^1.1.1
  location: ^2.3.5
  firebase_core: ^0.4.0+9
  firebase_database: ^3.0.6
  firebase_auth: ^0.14.0+4


dev_dependencies:
  flutter_test:
    sdk: flutter




# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - logo_192.png
    - appbar_logo.png
    - assets/main_page/main_top_1.png
    - assets/main_page/main_top_2.png
    - assets/main_page/main_top_3.png
    - assets/main_page/main_top_4.png
    - assets/main_page/main_fb_slider.png
    - assets/venue_detail/venue_detail_slider.png
    - assets/venue_detail/venue_detail_address.png
    - assets/icons/icon_facebook.png
    - assets/icons/icon_instagram.png
    - assets/icons/icon_twitter.png
    - assets/icons/icon_youtube.png
    - assets/venue_list/venue_item_1.png
    - assets/venue_list/venue_item_2.png
    - assets/venue_list/venue_item_3.png
    - assets/venue_list/venue_item_4.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
